### PR TITLE
Added the ability to specify an external camelizer

### PR DESCRIPTION
**Pull request by odino**
Hola there :)

We've bumped into this module and wanted to use it to implement versioning in some of our responses (think v1 --> snake case / v2 --> camelCase), though we realized it's quite slow as it needs to camelize all keys each and every time.

Wanted to add an option to specify a custom camelizer -- for example this is what we have:

``` js
const camelCase = memoize(require('camelcase'), {primitive: true, length: 1});

camelCaseKeys(obj, {
      deep: true,
      camelCase: memoizedCamelCase,
})
```

Do you need tests?

### CODE REVIEW

**Comment by sindresorhus** [comment]
>  though we realized it's quite slow as it needs to camelize all keys each and every time.

Did you actually experience and measure this or is it an assumption? I ask because `camelcase` only does some simple string operations, so should in theory be pretty fast. What does your strings that needs to be camelCased look like? (You don't have to share the exact strings, just the equivalent length and casing). How many keys approximately?

**Comment by odino** [comment]
@sindresorhus quite slower in my opinion :) Check this: https://gist.github.com/odino/ec691cc2e5fd02ea387030f114c7f8cd

This is a sample of what I get locally:

```
regular: 0.349ms
memoized: 0.136ms
regular: 0.330ms
memoized: 0.136ms
regular: 0.336ms
memoized: 0.131ms
regular: 0.340ms
memoized: 0.138ms
regular: 0.340ms
memoized: 0.128ms
regular: 0.345ms
memoized: 0.129ms
regular: 0.339ms
memoized: 0.126ms
regular: 0.336ms
memoized: 0.130ms
regular: 0.344ms
memoized: 0.129ms
regular: 0.335ms
memoized: 0.142ms
regular: 0.412ms
memoized: 0.134ms
regular: 0.507ms
memoized: 0.130ms
```

And on bigger response it becomes quite evident:

```
regular: 0.940ms
memoized: 0.303ms
regular: 0.945ms
memoized: 0.301ms
regular: 0.932ms
memoized: 0.300ms
regular: 0.991ms
memoized: 0.303ms
regular: 0.930ms
memoized: 0.304ms
regular: 0.926ms
memoized: 0.302ms
regular: 0.887ms
memoized: 0.298ms
regular: 0.894ms
memoized: 0.301ms
regular: 1.073ms
memoized: 0.415ms
regular: 1.097ms
memoized: 0.308ms
regular: 0.989ms
memoized: 0.305ms
```

In our API we got it down from 6ms to 1ms by using a memoized function.

**Comment by sindresorhus** [comment]
In https://gist.github.com/odino/ec691cc2e5fd02ea387030f114c7f8cd, all the keys are already camelCased though.

I'm just trying to think of how we can improve this for everyone, not just if you set a memoized function yourself. I have some optimizations in mind. Will try it out later.

**Comment by odino** [comment]
Sorry, used a random [json generator](http://www.json-generator.com/) to generate the object to camelize -- in any case the point is that camelizing is quite slow as opposed to caching the operation. My advice is to implement memoization in the camelcase module directly as, not matter what, looking up an entry in a map is always going to be faster than looping through the string to camelize it.

But then you need to think of how big you want your cache to be and so on, so you eventually end up using modules like memoizee :) and I didnt want to add a new dep here.

**Comment by odino** [comment]
@sindresorhus any news here? sorry to bother :)

**Comment by sindresorhus** [comment]
I've improved the performance of `camelcase` in https://github.com/sindresorhus/camelcase/commit/e7751f7b622ec64ef6e5e9b3e02c44fa77e1f4cd. I've also improved the performance here and added a LRU cache: https://github.com/sindresorhus/camelcase-keys/commit/5d6421aedf96733b9fa4792182f4db56782388c6

Can you try it out?

In the benchmark it resulted in a significant speed-up:

```
          19,281 op/s » npm
          74,622 op/s » master
```

(Using Node.js 7.8.0)

**Comment by odino** [comment]
LGTM :+1: 

```
regular: 0.120ms
memoized: 0.120ms
```

**Pull request closed without merging**
